'use client';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { isSupabaseConfigured, supabase } from '../supabase/client';

type Role='her'|'him';
type Message={id:string;room_id:string;sender:Role;content:string;her_seen:boolean;him_seen:boolean;created_at:string};
async function getRoomId():Promise<string|null>{const{data,error}=await supabase.from('rooms').select('id').order('created_at',{ascending:true}).limit(1).maybeSingle();if(error)throw error;return data?.id??null;}
async function getUnreadCounts(roomId:string){const{data,error}=await supabase.from('messages').select('sender,her_seen,him_seen').eq('room_id',roomId);if(error)throw error;return{her:(data??[]).filter(r=>r.sender==='him'&&!r.her_seen).length,him:(data??[]).filter(r=>r.sender==='her'&&!r.him_seen).length};}

function Chat({role,onBack}:{role:Role;onBack:()=>void}){
 const[roomId,setRoomId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState(false),[search,setSearch]=useState(''),[reply,setReply]=useState<Message|null>(null),[editing,setEditing]=useState<Message|null>(null),[pinned,setPinned]=useState<string[]>([]);
 const bottomRef=useRef<HTMLDivElement>(null),inputRef=useRef<HTMLInputElement>(null);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?messages.filter(m=>m.content.toLowerCase().includes(q)):messages;},[messages,search]);
 async function refreshMessages(id:string){const{data,error}=await supabase.from('messages').select('*').eq('room_id',id).order('created_at',{ascending:true});if(!error)setMessages((data??[])as Message[]);}
 useEffect(()=>{let alive=true;let channel:ReturnType<typeof supabase.channel>|null=null;async function initialize(){setLoading(true);setError('');if(!isSupabaseConfigured()){setError('Supabase is not configured.');setLoading(false);return;}try{const id=await getRoomId();if(!alive)return;if(typeof id!=='string'){setError('The Just Us chat room was not found.');setLoading(false);return;}setRoomId(id);const{data,error:messagesError}=await supabase.from('messages').select('*').eq('room_id',id).order('created_at',{ascending:true});if(!alive)return;if(messagesError)setError(messagesError.message);else setMessages((data??[])as Message[]);setLoading(false);channel=supabase.channel(`just-us-messages-${id}-${role}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`room_id=eq.${id}`},payload=>{if(!alive)return;const m=payload.new as Message;setMessages(c=>c.some(x=>x.id===m.id)?c:[...c,m]);}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'messages',filter:`room_id=eq.${id}`},payload=>{if(!alive)return;const m=payload.new as Message;setMessages(c=>c.map(x=>x.id===m.id?m:x));}).on('postgres_changes',{event:'DELETE',schema:'public',table:'messages',filter:`room_id=eq.${id}`},payload=>{if(!alive)return;setMessages(c=>c.filter(x=>x.id!==payload.old.id));}).subscribe(status=>{if(!alive)return;setOnline(status==='SUBSCRIBED');if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setError('Realtime connection unavailable. Messages will still sync automatically.');});}catch(caught){if(alive)setError(caught instanceof Error?caught.message:'Unable to open the chat.');setLoading(false);}}void initialize();return()=>{alive=false;setOnline(false);if(channel)void supabase.removeChannel(channel);};},[role]);
 useEffect(()=>{const id=roomId;if(typeof id!=='string')return;let active=true;const poll=async()=>{if(active)await refreshMessages(id);};const timer=window.setInterval(()=>void poll(),1000);return()=>{active=false;window.clearInterval(timer);};},[roomId]);
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth'});},[messages]);
 useEffect(()=>{const id=roomId;if(typeof id!=='string'||!messages.length)return;const unseenIds=messages.filter(m=>m.sender!==role&&(role==='her'?!m.her_seen:!m.him_seen)).map(m=>m.id);if(!unseenIds.length)return;void supabase.rpc('mark_seen',{p_message_ids:unseenIds,p_viewer:role});},[messages,role,roomId]);
 async function send(event?:FormEvent<HTMLFormElement>){event?.preventDefault();const content=text.trim();const id=roomId;if(!content||sending||typeof id!=='string')return;setSending(true);setError('');if(editing){const{data,error:e}=await supabase.from('messages').update({content}).eq('id',editing.id).eq('room_id',id).select('*').single();if(e)setError(`Edit failed: ${e.message}`);else{setMessages(c=>c.map(m=>m.id===editing.id?(data as Message):m));setEditing(null);setText('');}setSending(false);return;}
 const localId=crypto.randomUUID();const optimistic:Message={id:localId,room_id:id,sender:role,content,her_seen:role==='her',him_seen:role==='him',created_at:new Date().toISOString()};setMessages(c=>c.some(x=>x.id===localId)?c:[...c,optimistic]);setText('');setReply(null);
 const{error:sendError}=await supabase.from('messages').insert({room_id:id,sender:role,content,her_seen:role==='her',him_seen:role==='him'});
 if(sendError){setMessages(c=>c.filter(x=>x.id!==localId));setError(`Message failed: ${sendError.message}`);setText(content);}else{void refreshMessages(id);requestAnimationFrame(()=>inputRef.current?.focus());}setSending(false);}
 async function deleteMessage(id:string){if(!window.confirm('Delete this message?'))return;const currentRoomId=roomId;if(typeof currentRoomId!=='string')return;const{error:e}=await supabase.from('messages').delete().eq('id',id).eq('room_id',currentRoomId);if(e)setError(`Delete failed: ${e.message}`);else setMessages(c=>c.filter(m=>m.id!==id));}
 async function deleteChat(){const id=roomId;if(typeof id!=='string'||!window.confirm('Delete the entire chat? This cannot be undone.'))return;const{error:e}=await supabase.from('messages').delete().eq('room_id',id);if(e)setError(`Chat deletion failed: ${e.message}`);else setMessages([]);}
 function editMessage(m:Message){setEditing(m);setReply(null);setText(m.content);requestAnimationFrame(()=>inputRef.current?.focus());}
 function pinMessage(m:Message){setPinned(p=>p.includes(m.id)?p.filter(x=>x!==m.id):[...p,m.id]);}
 return <main className="chat-page"><header className="chat-header"><button type="button" onClick={onBack}>←</button><div><b>💙 Just Us</b><small>{online?'● Live':loading?'○ Connecting…':'○ Offline'}</small></div><button type="button" onClick={()=>setSearch(s=>s?'':s)} aria-label="Search">⌕</button><button type="button" onClick={()=>void deleteChat()}>🗑️</button></header>{search!==''&&<div style={{padding:'8px 14px',borderBottom:'1px solid #edf0f3'}}><input className="name-entry" autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search messages…"/></div>}<section className="messages" aria-live="polite">{loading?<div>Opening your little corner…</div>:visible.length===0?<div className="empty"><span>♡</span><strong>{search?'No messages found':'Nothing here yet'}</strong><span>{search?'Try another word.':'Say hello. It can be anything.'}</span></div>:visible.map(m=><article key={m.id} className={m.sender===role?'mine':'theirs'}>{reply?.id===m.id&&<small style={{marginBottom:4,color:'#6b7280'}}>Replying to this message</small>}<div><div className={`bubble ${m.sender}`}>{pinned.includes(m.id)&&<span title="Pinned">📌 </span>}{m.content}</div><time>{new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div><div style={{display:'flex',gap:4,marginTop:3}}><button type="button" onClick={()=>setReply(m)} title="Reply">↩</button><button type="button" onClick={()=>navigator.clipboard?.writeText(m.content)} title="Copy">⧉</button><button type="button" onClick={()=>pinMessage(m)} title="Pin">📌</button>{m.sender===role&&<button type="button" onClick={()=>editMessage(m)} title="Edit">✎</button>}{m.sender===role&&<button type="button" onClick={()=>void deleteMessage(m.id)} title="Delete">×</button>}</div></article>)}<div ref={bottomRef}/></section>{error&&<div className="error">{error}</div>} {(reply||editing)&&<div style={{padding:'7px 14px',borderTop:'1px solid #edf0f3',background:'#fafafa',fontSize:12,color:'#6b7280'}}>{editing?'Editing message':'Replying to'} <b>{(editing||reply)?.content.slice(0,70)}</b><button type="button" onClick={()=>{setReply(null);setEditing(null);setText('')}} style={{float:'right',border:0,background:'transparent'}}>×</button></div>}<form onSubmit={send} className="composer"><input ref={inputRef} value={text} onChange={e=>setText(e.target.value)} placeholder={editing?'Edit message…':'Write something…'} maxLength={4000} autoComplete="off" autoFocus/><button type="submit" disabled={!text.trim()||sending}>{editing?'✓':sending?'…':'↑'}</button></form></main>;
}
export default function Home(){const[role,setRole]=useState<Role|null>(null),[name,setName]=useState(''),[counts,setCounts]=useState({her:0,him:0}),[ready,setReady]=useState(false);const normalized=name.trim().toLowerCase();const matchedRole:Role|null=normalized==='aarna'?'her':normalized==='akshat'?'him':null;useEffect(()=>{let alive=true;let channel:ReturnType<typeof supabase.channel>|null=null;async function load(){if(!isSupabaseConfigured())return;try{const roomId=await getRoomId();if(typeof roomId!=='string'||!alive)return;setCounts(await getUnreadCounts(roomId));channel=supabase.channel(`just-us-unread-${roomId}`).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`room_id=eq.${roomId}`},async()=>{try{if(alive)setCounts(await getUnreadCounts(roomId));}catch{}}).subscribe();}catch{}}void load();return()=>{alive=false;if(channel)void supabase.removeChannel(channel);};},[]);useEffect(()=>{if(matchedRole){const t=window.setTimeout(()=>setReady(true),250);return()=>window.clearTimeout(t);}setReady(false);},[matchedRole]);if(role)return <Chat role={role} onBack={()=>{setRole(null);setName('');setReady(false);}}/>;const currentCount=matchedRole==='her'?counts.her:matchedRole==='him'?counts.him:0;return <main className="entry"><section className="entry-card"><div className="eyebrow">JUST US</div>{!ready?<><h1>A little place for us ❤️</h1><p>Type your name to continue.</p><input className="name-entry" autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Type your name…" autoComplete="off"/>{name.trim()&&!matchedRole&&<small style={{display:'block',marginTop:12,opacity:.65}}>Enter your name</small>}</>:<><h1>Welcome, {name} ❤️</h1><p>Your space is ready.</p><button type="button" className="role-buttons" onClick={()=>setRole(matchedRole!)} style={{width:'100%',border:0,cursor:'pointer'}}>{currentCount>0?`💌 New Messages (${currentCount})`:'💬 New Messages'}<small style={{display:'block',marginTop:5,opacity:.7}}>Click to open your chat</small></button></>}</section></main>}
